# This is a configuration for running a Piped. See https://pipecd.dev/docs/user-guide/managing-piped/configuration-reference/ for details.
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  apiAddress: localhost:9080
  projectID: tutorial
  pipedID: <YOUR_PIPED_ID> # [EDIT_HERE] Piped ID is generated on the console.
  pipedKeyFile: <YOUR_PIPED_KEY_FILE_PATH> # [EDIT_HERE] The path to the Piped Key file.
  repositories:
    - repoID: tutorial-repo
      remote: https://github.com/<YOUR_GITHUB_ACCOUNT_ID>/<YOUR_REPOSITORY_NAME>.git # [EDIT_HERE] The HTTPS URL of your repository.
      branch: main
  syncInterval: 15s
  platformProviders:
    # [EDIT_HERE] Uncomment one of followings:
    
    ## [1] Kubernetes
    # - name: my-kubernetes
    #   type: KUBERNETES
    #   config:
    #     kubeconfigPath: <YOUR_KUBECONFIG_PATH> # Your piped will connect to your cluster with this config.

    ## [2] Google Cloud > Cloud Run
    # - name: my-cloudrun
    #   type: CLOUDRUN

    ## [3] AWS > ECS
    # - name: my-ecs
    #   type: ECS
    #   config:
    #     region: <YOUR_AWS_REGION> # [EDIT_HERE] e.g. ap-northeast-1
    #     profile: default # Name of your AWS credentials profile.

    ## [4] AWS > Lambda
    # - name: my-lambda
    #   type: LAMBDA
    #   config:
    #     region:  <YOUR_AWS_REGION>  # [EDIT_HERE] e.g. ap-northeast-1
    #     profile: default # Name of your AWS credentials profile.

    ## [5] Terraform
    # - name: my-terraform
    #   type: TERRAFORM
