# This file defines the behavior of deploying a simple ECS service with a task definition.
apiVersion: pipecd.dev/v1beta1
kind: ECSApp
spec:
  name: simple-app
  input:
    serviceDefinitionFile: servicedef.yaml
    taskDefinitionFile: taskdef.yaml
    targetGroups:
      primary:   # The service will receive traffic via this target group.
        targetGroupArn: <YOUR_TARGET_GROUP_ARN> # [EDIT_HERE]
        containerName: web
        containerPort: 80
  description: |
    This app demonstrates how to deploy an ECS application under an ELB with [Quick Sync](https://pipecd.dev/docs/concepts/#sync-strategy) strategy.\
    cf. [adding a new app](https://pipecd.dev/docs/user-guide/managing-application/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/#ecs-application)